### ISSUE TITLE
When Options page is opened, some words are spoken

### ISSUE THREAD

**Issue by ceilican** [OiWorld/MindTheWord#196]
I suspect this is a bug in the "Speak The Word" feature.

Although the pronunciation is not very clear, it seems that the following three words are spoken: "the", "vu" and "vu".

It takes about 10 seconds for the pronunciation of these three words to start. It pauses for 3 seconds between the words.

The attached screenshot shows that sound is being produced by the tab containing the options page.

This problem happens when I open the options page either through "chrome://extensions/" or through the icon in the top right corner. It does not happen when I reload the options page.

<img width="1116" alt="screen shot 2016-09-20 at 13 43 47" src="https://cloud.githubusercontent.com/assets/1809436/18680091/9f97bd20-7f38-11e6-90fe-546eaf895cae.png">

**Comment by boro741** [comment]
@ceilican  u mean the words "the", "vu" and "vu" that are spoken when the page is loaded to be removed.

**Comment by ceilican** [comment]
Exactly. Do you know why this is happening?

**Comment by sanket0211** [comment]
The sound is coming due to the file **/MindTheWord/dist/views/includes/advanced.html** .
On the line no. 164 in the above file, we have HTML code : **<iframe width="100%" height="80%" src="https://www.youtube.com/embed/b1oLm_Y4p-M?autoplay=1"></iframe>** . Due to this line of code, the youtube video is **playing automatically** in the background. This youtube video contains the sounds which are being heard on the main page. 
I guess the solution to this would be removing the autoplay option from the youtube video URL.
