### ISSUE TITLE
Not able to get working on Chrome for Mac

### ISSUE THREAD

**Issue by mattcoker** [OiWorld/MindTheWord#28]
Throws the following error on all pages tested on, across multiple domains.
`mindTheWord running`
`Options received:`
`activation: true`
`ngramMin: 1`
`ngramMax: 1`

`VM70 extensions::uncaught_exception_handler:8 Error in event handler for (unknown):`
`HierarchyRequestError: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to insert the rule.`
`at injectCSS (chrome-extension://fabjlaokbhaoehejcoblhahcekmogbom/MindTheWord.js:7:27)`
`at chrome-extension://fabjlaokbhaoehejcoblhahcekmogbom/MindTheWord.js:201:16`

EDIT: Additional Information
Chrome for Mac Version 39.0.2171.95 (64-bit)
OSX Yosemite 10.10.1

**Comment by Ceilican** [comment]
Thanks for the bug report. I wasn't able to reproduce this issue here. Have a look on the screenshot below.

I use Chrome for Mac Version 39.0.2171.95 (64-bit)  (the same as yours)
and OSX Yosemite 10.10.1 (again the same as yours).

Could you give me more information, so that i can try to reproduce the error here? On which pages did the error occur? Have you tried to close and reopen Chrome? Are there any other installed extensions that might be interfering with MindTheWord somehow?

![screen shot 2015-01-15 at 08 36 51](https://cloud.githubusercontent.com/assets/1809436/5753953/c5f2a934-9c91-11e4-938e-5fe74136622a.png)

**Comment by mattcoker** [comment]
I believe this issue was due to needing to restart chrome after install. Been working great for me ever since.

**Comment by Ceilican** [comment]
Nice to know that everything is fine now!
