### ISSUE TITLE
For some users, changing translation configuration does not seem to help

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#32]
> Hello, I just downloaded the extension today, but for some reason it won't translate into any language except the default Latin and Italian the ext. comes with. I deleted them to add the language from the list I want to learn, but nothing happens. I can restart, new page, on/off... nothing. And the toggle button does nothing at all. Please help?

**Comment by sakshamsaxena** [comment]
#39 is similar. I dunno where we are at this. Haven't faced this problem personally though.

**Comment by Ceilican** [comment]
It might be related to #39, but not necessarily. I wasn't able to reproduce these two issues in my computer. Therefore, it is hard for me to say.

**Comment by srikar0896** [comment]
hello sir,the error may be due to  parsing undefined. When JSON.parse() is called, you're passing in S('savedPatterns'), which in turn tries to access cachedStorage['savedPatterns'], but that starts as undefined, So,It is throwing (Unexpected token u-options.js)which can't be parsed.So,cachedStorage must be initialized.

**Comment by sakshamsaxena** [comment]
Isn't there a test written for this? Food for thought?

**Comment by Ceilican** [comment]
> hello sir,the error may be due to parsing undefined. 

But the question is why it is undefined only for some users.
