### ISSUE TITLE
Amount of translated words is much lower than specified in the translation configuration

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#37]
Even when we specify 45% of translation, only a few words are translated.

**Comment by chris838** [comment]
The percentage is taken after blacklisting, removing proper nouns etc. When we specify 45% do we mean 45% of all words on the page or 45% of the words that are suitable for translation (currently I think you're using the latter).

**Comment by Ceilican** [comment]
We currently do not remove proper nouns, but we do end up filtering many other "words" besides the blacklist. Initially the text is split into a list of "words" separated by space, but these words may contain numerical digits, punctuation marks and other things that might make them unsuitable for translation. We filter out these unsuitable words.

Therefore, you are right: we mean 45% of the *suitable* words.

However, I still have the impression that sometimes much less than 45% of the suitable words are translated.

Maybe the suitability filter is stricter than it needs to be. Or maybe some translations are being lost afterwards, for unknown reasons.



  We filter the "words" that contain these and other nasty   (e.g. sequents of characters containing digits or pun)

**Comment by Ceilican** [comment]
Even if we succeed in translating, for example, 45% of the suitable words, this is still typically much less than 45% of *all* words, and this can be perceived as a problem from the user's perspective.

**Comment by Ceilican** [comment]
I have just seen that you committed something (https://github.com/chris838/MindTheWord/commit/e1d027d36781010cb15a3c98d84b99efa737abd3) that seems to fix this. I will close this issue after merging back your fork.

**Comment by alexklibisz** [comment]
@Ceilican Is this still an existing issue? It's difficult for me to measure without just "eyeballing" it. If it is still I problem then I can take a look at it as part of my GSOC application process.

**Comment by Ceilican** [comment]
@alexklibisz It is still an issue. I think there are many reasons why the translation proportion turns out to be much smaller than the translation proportion specified in the options page. This issue is probably caused by many "bugs".

We don't need to be obsessed with precision here, but currently it is a bit too imprecise...

**Comment by ankit-m** [comment]
### Bug
@Ceilican the bug is in `deepHTMLReplacement` with the following lines of code
```javascript
  } else if (node.nodeType == Node.ELEMENT_NODE && (badTags.indexOf(node.tagName) <= -1)) {
    var child = node.firstChild;
    while (child) {
      deepHTMLReplacement(child, tMap, iTMap);
      child = child.nextSibling;
    }
  }
```

The problem was that it skipped the text elements between various tags. For example, the HTML was -
```html
<p>
    <a href="">Hello</a>
    some text
    <a href="">hello again</a>
    .. so on 
</p>
```

It would skip `..so on` because it was not checking all the children. 

### Solution
This was fixed as follows.

```javascript
  } else if (node.nodeType === Node.ELEMENT_NODE && (badTags.indexOf(node.tagName) <= -1)) {
    var innerNodes = node.childNodes;
    for (var index = 0; index < innerNodes.length-1; index++) {
      deepHTMLReplacement(innerNodes[index], tMap, iTMap);
    }
  }
```

Also, the `+ 24` in translationProbability was removed as it was causing more translations. Now that the `deepHTMLReplacement` is fixed.
```javascript
r.translationProbability + 24, // ToDo: I am increasing the probability here, to compensate for decreases caused elsewhere. This should be fixed.
```

### Test
**55% English to German**
Old: The translations are grouped and first two don't have any translations
![sci_err](https://cloud.githubusercontent.com/assets/9019878/13905049/5b0ade4c-eeda-11e5-90cc-21e2f9718494.png)

Fixed: All paragraphs have proper translations. 
![sci_fix](https://cloud.githubusercontent.com/assets/9019878/13905052/81753758-eeda-11e5-9d52-7c9fcde07637.png)
