### ISSUE TITLE
Google Translate error

### ISSUE THREAD

**Issue by ankit-m** [OiWorld/MindTheWord#81]
Google Translate API v2 is a paid service. The existing implementation uses request which causes 503 error. Following is the error generated 

![translate_error](https://cloud.githubusercontent.com/assets/9019878/13635231/6f8595a0-e620-11e5-96e2-da192d85fdee.png)

To use Google Translate, we have to make a developer account and use the key after payment (which is around $20).

**Comment by Ceilican** [comment]
Yes. It used to be free when I first implemented MTW. Then for a while it continued to be free, but with a very low limit of number of characters per month. And it seems that now it is not free at all. That's why another developer added Yandex later.

Even if we paid $20, I think the key still allows only a limited number of translations, which would be insufficient for the MTW's 10000+ users.

We could allow each user to add his own Google Translate key, in the same way we did for Yandex (except that Yandex's key is free). That would be a nice feature to implement.

**Comment by ankit-m** [comment]
Yes definitely. But right now the default is set to Google. When someone downloads it for the first time, they try it without putting the Yandex key. But nothing shows up (because of the error). As a result, they think that the extension is not working.

So I think we should set the default to Yandex and ask them to use a key. What do you think?

**Comment by Ceilican** [comment]
> So I think we should set the default to Yandex and ask them to use a key. What do you think?

Yes, definitely.

**Comment by ankit-m** [comment]
@Ceilican on it.

**Comment by Stormteller** [comment]
@Ceilican And what about Bing Translator? It has up to 2M characters translation for free

**Comment by Ceilican** [comment]
@Stormteller , It would be a good idea to add Bing Translator as well.
